### ISSUE TITLE
op values are not cross checked with interaction level information

### ISSUE THREAD

**Issue by egekorkan** [thingweb/thingweb-playground#116]
In the TD spec it is allowed to have an interaction with `"readOnly":true` and have an `op` in the same interaction's `forms` with `writeproperty`. Similar with `writeOnly` or `observable`. I think that these should be checked in the additional checks section.

**Comment by egekorkan** [comment]
@adriankast could you add it to the additional validation

**Comment by egekorkan** [comment]
In https://github.com/thingweb/thingweb-playground/issues/73 the 3rd item is exactly this.

**Comment by egekorkan** [comment]
This seems to still not work, i.e. inserting the following TD to the deployed version says valid for everything:
```json
{
	"id": "urn:simple",
	"@context": "https://www.w3.org/2019/wot/td/v1",
	"title": "MyLampThing",
	"description": "Valid TD copied from the spec's first example",
	"securityDefinitions": {
		"basic_sc": {
			"scheme": "basic",
			"in": "header"
		}
	},
	"security": [
		"basic_sc"
	],
	"properties": {
		"status": {
			"type": "string",
            "readOnly":true,
			"forms": [
				{
					"href": "https://mylamp.example.com/status",
					"op": "writeproperty",
					"contentType": "application/json"
				}
			]
		}
	}
}
```

**Comment by adriankast** [comment]
It doesn't work in the deployed version that is correct, could it be an older version?
Because it also doesn't even show the field `readWriteOnly ` in the details

**Comment by adriankast** [comment]
When checking with the `new-arch` branch:
![grafik](https://user-images.githubusercontent.com/55034043/93061850-6affa700-f674-11ea-8cbb-1839514c77ee.png)
![grafik](https://user-images.githubusercontent.com/55034043/93061900-7d79e080-f674-11ea-9cf3-a725c80da572.png)
![grafik](https://user-images.githubusercontent.com/55034043/93061927-85d21b80-f674-11ea-81f2-420b875fbc54.png)
