### ISSUE TITLE
Typo checks

### ISSUE THREAD

**Issue by fatadel** [thingweb/thingweb-playground#122]
I fed in a Thing Description with a typo in the description keyword (which was desciption), and it was validated to Ok. Is that an intended behaviour?

**Comment by egekorkan** [comment]
Yes this is the intended behavior since it is possible to add custom keywords. It cannot tell that `desciption` is a mistyped `description`.

**Comment by fatadel** [comment]
But aren't custom keywords prefixed with `prefix:`, like `iot:` for example? If so it should be easy to distinguish the cases. And even if it's not like that, I think it is a good feature request to at least fire a warning that it might be a typo when the used keywords are 1-2 characters different from the ones which are reserved TD keywords.

**Comment by egekorkan** [comment]
They should be but are not required to be prefixed. Not everyone wants to use the JSON-LD functionalities and write a vocabulary. Of course, you can write dummy vocabularies URIs.
However, your proposal on finding similar names is a good idea and I will try to integrate it as a new feature.

**Comment by fatadel** [comment]
Thank you very much, @egekorkan!

**Comment by egekorkan** [comment]
This can be used: https://stackoverflow.com/questions/57102484/find-difference-between-two-strings-in-javascript
