### ISSUE TITLE
There should be a way to disable continuous logging

### ISSUE THREAD

**Issue by egekorkan** [thingweb/thingweb-playground#123]
With a checkbox, it should be possible to do a clear log before each validation so that only the most recent log messages are shown.

@adriankast can you have a look at it?

**Comment by adriankast** [comment]
Sure I will include it

**Comment by adriankast** [comment]
![grafik](https://user-images.githubusercontent.com/55034043/85324295-de58a900-b4c9-11ea-949d-aad34010e9cc.png)
I have included a checkbox for it (with tooltip as you can see in the screenshot).

**Comment by egekorkan** [comment]
Looks good :) Will close when the redesign PR is ready

**Comment by adriankast** [comment]
Please link this issue in [PR125](https://github.com/thingweb/thingweb-playground/pull/125) @egekorkan  :)
