### ISSUE TITLE
Examples cannot be fetched

### ISSUE THREAD

**Issue by danielpeintner** [thingweb/thingweb-playground#128]
To reproduce the issue.
1. Go to http://plugfest.thingweb.io/playground/
2. Try to select an example from drop-down list
3. Dialog appears: e.g., "The JSON could not be fetched from the address:
https://raw.githubusercontent.com/thingweb/thingweb-playground/master/WebContent/Examples/Valid/simple.json"

**Comment by egekorkan** [comment]
Ah yes, we haven't deployed the new one yet, should be done soon :)

**Comment by egekorkan** [comment]
It is now deployed, closing :)
