### ISSUE TITLE
'old' TD version with interaction term is validated as correct

### ISSUE THREAD

**Issue by sebastiankb** [thingweb/thingweb-playground#13]
It seems, that 'old' TDs with the _interaction_ term are validated correct which should not be the case or at least provide a warning that non _properties_, _actions_, or _events_ term was used:

![image](https://user-images.githubusercontent.com/13832739/41855559-3690a7dc-7893-11e8-9003-0e36782bfad4.png)

**Comment by egekorkan** [comment]
Corrected. The warning check was being done for "interactions" instead of "interaction". This should be fixed now.
