### ISSUE TITLE
[MINOR UI PROPOSAL] Color Highlighting

### ISSUE THREAD

**Issue by danielpeintner** [thingweb/thingweb-playground#130]
I propose that the coloring for validation (with/or without default) and errors could/should be aligned with the drop-down shown for the examples.

see http://plugfest.thingweb.io/playground/

* green: all fine
* orange: missing defaults
* red: errrors

**Comment by adriankast** [comment]
I'm not sure whether I understand you proposal. The validation colors are actually the same as in the dropdown (see screenshots). 
Do you mean that the first two examples currently fail the default validation? (which I should change? @egekorkan ) 
![grafik](https://user-images.githubusercontent.com/55034043/90393507-31497980-e091-11ea-9f62-c4db52798dd9.png)
![grafik](https://user-images.githubusercontent.com/55034043/90393548-44f4e000-e091-11ea-8688-5ea1564f8f68.png)

**Comment by egekorkan** [comment]
Yes, the valid examples actually do not contain the default values which result in a yellow result. Instead of changing the examples, new simple TDs should be added that have the default values. The simple td should stay since it's the first one of the TD spec.

**Comment by adriankast** [comment]
Okay 👍

**Comment by danielpeintner** [comment]
> The simple td should stay since it's the first one of the TD spec.

Agree. But the color of the *current* SimpleTD should be yellow.... that's what I meant.
Sorry for not being clear enough :-)

**Comment by adriankast** [comment]
Okay good, yes sounds good! No problem I just wanted to be sure that we're talking about the same thing :) 
Is implemented and will be shipped with the next PR.

**Comment by egekorkan** [comment]
Deployed now, closing
