### ISSUE TITLE
Submit TD as gist feature

### ISSUE THREAD

**Issue by adriankast** [thingweb/thingweb-playground#132]
On the playground should be a button "submit as gist", which allows submitting the TD being edited to the Thingweb Github account. Unless other advise I would implement:
* GOOD: an node.js script listening on a port which accepts `Description`+`Name` as input, does the request to the GitHub API, responses with Status and the gist ID.
  `+` The private API Token can be kept secret
  `-` The script needs to be hosted by an node.js environment on the playground/another server
* Alternative: The request is made directly in the playground web script. This would allow extraction of the API key, which can be used to create/update/delete all Gists of the account.
In both cases the API Token will be inserted by a CD process and not visible in the repository.

**Comment by adriankast** [comment]
Is hosting the node.js script possible? @egekorkan :)

**Comment by egekorkan** [comment]
Yes, it is possible but would be better to make it frontend only. I do know the technical annoyances regarding that, i.e. if someone looks into the debug env. they will see the token which can be used maliciously.

**Comment by adriankast** [comment]
Okay, sure. I also think the malicious use is acceptable, since it is restricted to Gists.

**Comment by egekorkan** [comment]
I didn't want to so say that it must be done like that. Once playground is moved to Eclipse, they would have access to all the gists of the Eclipse foundation which is not acceptable. Just that if by some means it is done in frontend, it would make the deployment easier :)

**Comment by adriankast** [comment]
Oh okay, so what about one of these approaches:
1. Deploy a backend script (from a separate repository), which has an fixed url where it is reachable and thus shouldn't cause maintenance effort no matter how the frontend changes?
2. Create an GitHub account for the WoT-Playground where then all Gists will be submitted to, worst case scenario with putting everything in the frontend would then be that someone deletes submitted gists or tries to insert, e.g., malicious urls in the TDs. In anycase the Eclipse repository wouldn't be harmed.
? :)

**Comment by egekorkan** [comment]
Then let's go with option 1 :)

**Comment by adriankast** [comment]
Okay 👍

**Comment by adriankast** [comment]
I have implemented it a bit more...styled. 
![grafik](https://user-images.githubusercontent.com/55034043/92377249-2750ee80-f104-11ea-8eb1-0c7eb2db17af.png)
What do you think? We can of course switch to text :)

**Comment by egekorkan** [comment]
Looks really nice!

**Comment by adriankast** [comment]
Ooops wrong Issue, should of course be at #129

**Comment by adriankast** [comment]
Closing, since its deployed and working.
