### ISSUE TITLE
Editor window is pretty small on displays with high resolution

### ISSUE THREAD

**Issue by weigandjakob** [thingweb/thingweb-playground#136]
As the title states the editor window is pretty small for displays with high resolution with a pretty large unused white bar at the lower display part (see screenshots). Would it be possible to make the editor window variable in size or adapt the editor size to the display resolution? Maybe it would also be a possibility to adapt the layout to a column layout with the TD on the left and the options and validation output on the right side. These screenshot were taken with a display resolution of 1440x2560 (first) and 3840 × 2160 Pixel (second).
![image](https://user-images.githubusercontent.com/65398308/91355905-1f817800-e7ef-11ea-9253-6c6de6c48e29.png)
![image](https://user-images.githubusercontent.com/65398308/91356677-586e1c80-e7f0-11ea-967a-7a8f02feb46e.png)

**Comment by egekorkan** [comment]
@adriankast is having a look at it :)

**Comment by adriankast** [comment]
Should now be fine at least up to 4096x2160 (see screenshots) :)
But I guess if we really want to support larger screens it would also be necessary to scale font & buttons?...

![2560x1440](https://user-images.githubusercontent.com/55034043/93115420-1aac3780-f6bc-11ea-9172-86d20d4274ee.png)
2560x1440

![3840x2160](https://user-images.githubusercontent.com/55034043/93115417-197b0a80-f6bc-11ea-8843-192f77f807f2.png)
3840x2160

![4096x2160](https://user-images.githubusercontent.com/55034043/93115419-1a13a100-f6bc-11ea-8e75-d65655a07323.png)
4096x2160

comes with next PR

**Comment by adriankast** [comment]
Regarding the comment, making it variable in size will probably not work so easily, since Monaco editor uses the given display size to hardcode in his html frame so I guess it would require reloading the page on every size manipulation. Changing the console position to to the right would be possible but only make sense for large screens and large tds...

**Comment by egekorkan** [comment]
Looks nice, PR merged !

**Comment by weigandjakob** [comment]
Looks good. I personally did not have a problem with the font and button scaling but more scaling is usually better....
The other options were meant as suggestions. Perhaps they might be useful in the future, if the average display resolution increases further?

**Comment by adriankast** [comment]
Yes right, I also think for now it should be fine like this.
