### ISSUE TITLE
manual assertions only added?

### ISSUE THREAD

**Issue by SickHatt** [thingweb/thingweb-playground#137]
Hi there! This is more of a question than an issue.
I'm wondering what the idea behind the manual.csv assertions is.
I was looking in the code. It appears to just append them to the results array. I find this a bit odd, the status column is null than.

**Comment by egekorkan** [comment]
That is a good question! So there are some assertions in the TD spec that cannot be automatically tested, the implementation owner needs to say if they are implemented or not. For the web version, a separate window is shown where you can select them. For the cli, you need to change the manual.csv file or provide it via a path.

If for any assertion the status is null, it means that it has not been tested.

**Comment by egekorkan** [comment]
Given no further activity, I will close the issue. Feel free to reopen :)
