### ISSUE TITLE
Gistify backend related deployment problems

### ISSUE THREAD

**Issue by egekorkan** [thingweb/thingweb-playground#143]
1. In https://github.com/thingweb/thingweb-playground/blob/master/playground-web/config.js the code needs to be changed to change the deployment. 
2. The environment variables need to passed in the start command. It would be better to do it via dotenv package: https://www.npmjs.com/package/dotenv
3. Needs more testing but there are CORS problems

**Comment by adriankast** [comment]
I think we already solved 1. and 3.
I'm not sure what you mean with number 2. since under windows process env can access the environment variables of the system. If we use dotenv what would be the advantage in comparison to simply requiring a config.json or .js with the variables inside?

**Comment by egekorkan** [comment]
I didn't know about the fact that windows had that difference :/ Can it access even if the user can use them?
A JSON or JS file works as well but they need "special attention" to be not tracked by git

**Comment by adriankast** [comment]
I will check with Linux, I thought environment variables are available for node on every system?
Yes thats true, but the same should apply for `.env` files? See https://www.npmjs.com/package/dotenv#should-i-commit-my-env-file

**Comment by adriankast** [comment]
For me (Ubuntu 20.04), adding `export PLAYGROUND_USER_NAME="asdf"` to the bashrc and accessing it via `process.env` works, could this be possible under our target server?

**Comment by egekorkan** [comment]
Didn't think of bashrc ^^. All good then, closing
