### ISSUE TITLE
TD examples contain property "http:methodName"

### ISSUE THREAD

**Issue by adriankast** [thingweb/thingweb-playground#148]
In the example TDs included in the playground-core package, the field name `http:methodName` appears in several files. 
Is it an error and should be `htv:methodName` or am I missing something?
https://w3c.github.io/wot-binding-templates/#http-vocabulary
The properties are part of these valid TD examples:
* formOpArray
* formOpArrayWithDefaults
* JsonLdThing
* rootForms

**Comment by egekorkan** [comment]
Yes these are mistakes :) It used to be "http" as prefix

**Comment by adriankast** [comment]
Okay :)
