### ISSUE TITLE
False negative for multiLang

### ISSUE THREAD

**Issue by egekorkan** [thingweb/thingweb-playground#149]
The following TD shows the error of multiLangConsistency even though all titles and descriptions have `de` language.
```json
{
   "@context":[
      "https://www.w3.org/2019/wot/td/v1",
      {
         "cov":"http://www.example.org/coap-binding#"
      },
      {
         "saref":"https://w3id.org/saref#"
      }
   ],
   "securityDefinitions":{
      "basic_schema":{
         "scheme":"basic",
         "descriptions":{

         },
         "description":"Basic sec schema",
         "in":"query",
         "name":"querykey"
      }
   },
   "security":[
      "basic_schema"
   ],
   "@type":[
      "saref:LightSwitch"
   ],
   "titles":{
      "de":"Deutscher Titel"
   },
   "title":"English title",
   "descriptions":{
      "de":"Deutsche Beschreibung"
   },
   "description":"English description",
   "properties":{
      "echo":{
         "observable":false,
         "forms":[
            {
               "op":[
                  "readproperty"
               ],
               "href":"/echo",
               "contentType":"application/json"
            }
         ]
      }
   }
}
```

**Comment by adriankast** [comment]
The reason is that the content of the `title` property (and `description`) is not found in the multilang version. Thus the error message 
```
root_title is not on the multilang object at the same level
```

I don't no why or if this behaviour is wanted, but it has been there before I touched the code...so it seemed to be a feature not a bug ;)

If you use the TD below the validation says valid (added `en` tags with corresponding content):
```json
{
   "@context":[
      "https://www.w3.org/2019/wot/td/v1",
      {
         "cov":"http://www.example.org/coap-binding#"
      },
      {
         "saref":"https://w3id.org/saref#"
      }
   ],
   "securityDefinitions":{
      "basic_schema":{
         "scheme":"basic",
         "descriptions":{

         },
         "description":"Basic sec schema",
         "in":"query",
         "name":"querykey"
      }
   },
   "security":[
      "basic_schema"
   ],
   "@type":[
      "saref:LightSwitch"
   ],
   "titles":{
      "de":"Deutscher Titel",
      "en": "English title"
   },
   "title":"English title",
   "descriptions":{
      "de":"Deutsche Beschreibung",
      "en": "English description"
   },
   "description":"English description",
   "properties":{
      "echo":{
         "observable":false,
         "forms":[
            {
               "op":[
                  "readproperty"
               ],
               "href":"/echo",
               "contentType":"application/json"
            }
         ]
      }
   }
}
```

**Comment by egekorkan** [comment]
The TD spec says:

>  When title and titles or description and descriptions are present in a TD document, each title and description member SHOULD have a corresponding titles and descriptions member, respectively.

Thus, the current behavior of the playground is correct. @citrullin sadly your TD was not correct but this is a really detailed case where I am pretty sure anyone in the working group can make. Even I didn't remember this requirement, even though I have created the validation case.
 
Somewhat related issue here: https://github.com/w3c/wot-thing-description/issues/959

**Comment by egekorkan** [comment]
Closing since even the error message is accurate, @citrullin you can reopen it if you need to :)

**Comment by Citrullin** [comment]
> The TD spec says:
> 
> > When title and titles or description and descriptions are present in a TD document, each title and description member SHOULD have a corresponding titles and descriptions member, respectively.
> 
> Thus, the current behavior of the playground is correct. @Citrullin sadly your TD was not correct but this is a really detailed case where I am pretty sure anyone in the working group can make. Even I didn't remember this requirement, even though I have created the validation case.
> 
> Somewhat related issue here: [w3c/wot-thing-description#959](https://github.com/w3c/wot-thing-description/issues/959)

Okay, I get that. But why do I need to duplicate data? This seems not very intuitive to me. Why not making the titles and descriptions property mandatory and have some kind of default lang in the thing itself?

**Comment by egekorkan** [comment]
> Why not making the titles and descriptions property mandatory and have some kind of default lang in the thing itself?

That is quite interesting and if you need to declare a default language, there is even more redundant information, the TD would have the following `@context`
```json
{
   "@context":[
      "https://www.w3.org/2019/wot/td/v1",
      { "@language" : "en" }
   ],
...
}
```

In this TD, all the `title` and `description` should contain english text. I think relying on this mechanism and removing `title` would create more effort on TD processors but I personnaly do not care too much about Consumers requiring more resources, the Things should be optimized first I think.

Should this be a question/issue for the TD Task Force? What do you think @sebastiankb  :)

**Comment by egekorkan** [comment]
closing since the linked TD issue should result on something first. Can be reopened if needed
