### ISSUE TITLE
multiLangConsistency failed

### ISSUE THREAD

**Issue by Citrullin** [thingweb/thingweb-playground#160]
Validation fails, because 
`multiLangConsistency failed (Checks whether all titles and descriptions have the same language fields.)`

Do I get something wrong? If there are descriptions and titles in the TD, does every object need a description and title with that language? 

```
{
   "@context":[
      "https://www.w3.org/2019/wot/td/v1",
      {
         "cov":"http://www.example.org/coap-binding#"
      },
      {
         "saref":"https://w3id.org/saref#"
      }
   ],
   "securityDefinitions":{
      "basic_schema":{
         "scheme":"basic",
         "description":"Basic sec schema",
         "descriptions": {
             "de": "Basic security schema"
         },
         "in":"query",
         "name":"querykey"
      }
   },
   "security":[
      "basic_schema"
   ],
   "@type":[
      "saref:LightSwitch"
   ],
   "titles":{
      "de":"Deutscher Titel"
   },
   "title":"English title",
   "descriptions":{
      "de":"Deutsche Beschreibung"
   },
   "description":"English description",
   "properties":{
      "echo":{
         "observable":false,
         "forms":[
            {
               "op":[
                  "readproperty"
               ],
               "href":"/echo",
               "contentType":"application/json",
               "cov:methodName":"GET"
            }
         ]
      }
   }
}
```

**Comment by egekorkan** [comment]
Yes the reason is correct, there is also the following message: `root_title is not on the multilang object at the same level` and the issue https://github.com/thingweb/thingweb-playground/issues/149 and https://github.com/w3c/wot-thing-description/issues/985

So to sum up:
- There seems to be a general confusion about this. My personal opinion (that is not valid according to TD 1.0) is that your TD should be valid if you also put `en` in `@language` tag in the `@context`. This way, I know that the document is in English and I can create the german version of it from this one only. 
- If you are doing an implementation that produces TDs and has language negotiation capability, the current safe way is to have redundant information. In the future, hopefully it can be like in the bullet point.

**Comment by Citrullin** [comment]
> Yes the reason is correct, there is also the following message: `root_title is not on the multilang object at the same level` and the issue #149 and [w3c/wot-thing-description#985](https://github.com/w3c/wot-thing-description/issues/985)
> 
> So to sum up:
> 
>     * There seems to be a general confusion about this. My personal opinion (that is not valid according to TD 1.0) is that your TD should be valid if you also put `en` in `@language` tag in the `@context`. This way, I know that the document is in English and I can create the german version of it from this one only.
> 
>     * If you are doing an implementation that produces TDs and has language negotiation capability, the current safe way is to have redundant information. In the future, hopefully it can be like in the bullet point.

Ohh thanks. I completely forgot that one ^^ :D

**Comment by Citrullin** [comment]
@egekorkan Thanks for pointing me to the issues. Haven't worked on the implementation for some time. Works fine now :D 
```
{
   "@context":[
      "https://www.w3.org/2019/wot/td/v1",
      {
         "cov":"http://www.example.org/coap-binding#"
      },
      {
         "saref":"https://w3id.org/saref#"
      }
   ],
   "securityDefinitions":{
      "basic_schema":{
         "scheme":"basic",
         "descriptions":{
            "en":"Basic sec schema"
         },
         "description":"Basic sec schema",
         "in":"query",
         "name":"querykey"
      }
   },
   "security":[
      "basic_schema"
   ],
   "@type":[
      "saref:LightSwitch"
   ],
   "titles":{
      "en":"English title",
      "de":"Deutscher Titel"
   },
   "title":"English title",
   "descriptions":{
      "en":"English description",
      "de":"Deutsche Beschreibung"
   },
   "description":"English description",
   "properties":{
      "echo":{
         "observable":false,
         "forms":[
            {
               "op":[
                  "readproperty"
               ],
               "href":"/echo",
               "contentType":"application/json",
               "cov:methodName":"GET"
            }
         ]
      }
   }
}
```
