### ISSUE TITLE
*Strange* warning for temporary TD context

### ISSUE THREAD

**Issue by danielpeintner** [thingweb/thingweb-playground#168]
The TD work continues and used a temporary TD context `"http://www.w3.org/ns/td"`.

Using examples with this context fail with a rather strange message:
> Incorrect type. Expected "array".

For example try https://w3c.github.io/wot-thing-description/#simple-thing-description-sample

**Comment by egekorkan** [comment]
I can allow for the use of this context value but it is not in the validation schema at the moment.
The strange error message is due to the fact that it expects either the exact value or an array that contains the value in the way it is wanted.

**Comment by danielpeintner** [comment]
The reason why I mentioned the issue is that some people may grab some examples from the document and run into the issue without knowing what is going on... Not sure though what is the best way to solve the problem.

**Comment by egekorkan** [comment]
this context is "tolerated" for now
