### ISSUE TITLE
UI console seems to have strange layout

### ISSUE THREAD

**Issue by danielpeintner** [thingweb/thingweb-playground#169]
I did try to run some tests on http://plugfest.thingweb.io/playground/

The UI, especially the console looks somewhat strange... pushed to the right corner in Firefox and Google Chrome (not using the full width et cetera).

![grafik](https://user-images.githubusercontent.com/11281461/102505742-a7331100-4082-11eb-90ee-75e43818f854.png)

**Comment by egekorkan** [comment]
Interesting, that is indeed not normal. Could you share your screen resolution? Also this behavior sometimes disappears after refreshing.

We actually test how the UI looks in different resolutions [here](https://github.com/thingweb/thingweb-playground/actions/runs/407997536) and the last screenshots are ok :/ Any other detail would be appreciated to find what causes this behavior

**Comment by danielpeintner** [comment]
My screen resolution is 1920 x 1080.

I _believe_ the problem is that the console expands underneath the footer. Or put differently, the footer is on top of the console and the footer is not at end of the page.

**Comment by egekorkan** [comment]
I think I have fixed it in the V1.1 branch. Not deployed yet

**Comment by egekorkan** [comment]
Deployed
