### ISSUE TITLE
Observable default missing

### ISSUE THREAD

**Issue by danielpeintner** [thingweb/thingweb-playground#211]
The following snippet reports all green lights on http://plugfest.thingweb.io/playground/
*  JSON validation
* JSON Schema validation
* (With Defaults) JSON Schema validation
* JSON-LD validation
* Additional Checks

I don't think this is correct since observable is missing for the property.

```
{
	"@context": "https://www.w3.org/2019/wot/td/v1",
	"properties": {
		"t1": {
			"forms": [{
				"contentType": "application/json",

				"href": "coap://mything.example.com:5683/temp",
				"op": ["readproperty"]
			}],
			"readOnly": false,
			"type": "boolean",
			"writeOnly": false
		}
	},
	"title": "MyThing1",
	"securityDefinitions": {
		"basic_sc": {
			"scheme": "basic",
			"in": "header"
		}
	},
	"security": "basic_sc"
}
```

**Comment by egekorkan** [comment]
That is a correct observation. Observable was a not with a default value before :) Adding to v1.1

**Comment by egekorkan** [comment]
fixed
