### ISSUE TITLE
Default value section misses op default for Thing

### ISSUE THREAD

**Issue by danielpeintner** [thingweb/thingweb-playground#212]
The [Default Value Definitions](https://w3c.github.io/wot-thing-description/#sec-default-values) section specifies default values for forms and differentiates between:
* If defined within an instance of PropertyAffordance
* If defined within an instance of ActionAffordance
* If defined within an instance of EventAffordance

It misses the default value for the [Thing](https://w3c.github.io/wot-thing-description/#thing) itself which may have forms also.

**Comment by egekorkan** [comment]
I think I don't understand the issue. Do you mean that default values of `op` should be generated for the Thing level forms?

**Comment by danielpeintner** [comment]
Sorry, I opened the issue in the wrong repo https://github.com/w3c/wot-thing-description/issues/1294
