### ISSUE TITLE
Playground does not accept href with ws:

### ISSUE THREAD

**Issue by danielpeintner** [thingweb/thingweb-playground#234]
Please find attached a simple example with `ws:` `href`

The error is as follows:
```
X JSON Schema validation failed:
> data/events/overheating/forms/0/href must match format "iri-reference"

```

Input for http://plugfest.thingweb.io/playground/
 
```
{
	"id": "urn:simpleWithDefaults",
	"@context": "https://www.w3.org/2019/wot/td/v1",
	"title": "MyLampThing",
	"description": "Valid TD copied from the spec's first example",
	"securityDefinitions": {
		"basic_sc": {
			"scheme": "basic",
			"in": "header"
		}
	},
	"security": [
		"basic_sc"
	],
	"events": {
		"overheating": {
			"data": {
				"type": "string"
			},
			"forms": [
				{
					"href": "ws://mylamp.example.com/oh",
					"op": "subscribeevent",
					"contentType": "application/json"
				}
			]
		}
	}
}
```

**Comment by egekorkan** [comment]
This is due to library that we use to validate iri-reference which does not have ws in the list of protocols. TD has decided to remove format so this will not be an issue anymore

**Comment by danielpeintner** [comment]
Not sure if you mean https://github.com/w3c/wot-thing-description/issues/956#issuecomment-1057131388 but there we only decided 

> we will remove format iri-reference from the schema

Shall we remove all "format" terms?

**Comment by egekorkan** [comment]
Fixed, we will not remove all format terms
