### ISSUE TITLE
Console text is not wrapped

### ISSUE THREAD

**Issue by egekorkan** [thingweb/thingweb-playground#24]
Since the error messages can be long sometimes, the text containing the error message should be wrapped in the console to match the width of the console

**Comment by adriankast** [comment]
Should work with the new architecture, problem (from my understanding) was that the `pre` tag has own wrapping rules. Adding
```css
white-space: pre-wrap;
```
seems to solve it. Found it [here](https://stackoverflow.com/questions/248011/how-do-i-wrap-text-in-a-pre-tag).

**Comment by egekorkan** [comment]
Sounds good :) Will close when the redesign PR is ready

**Comment by adriankast** [comment]
Should be fixed with [PR125](https://github.com/thingweb/thingweb-playground/pull/125) -> please link this issue in the PR @egekorkan if correct :).

**Comment by egekorkan** [comment]
Done :)

**Comment by egekorkan** [comment]
Fixed via #125
