### ISSUE TITLE
New Assertions for June Testfest

### ISSUE THREAD

**Issue by egekorkan** [thingweb/thingweb-playground#258]
Here is a manually generated list of assertions that we need to implement for automatic assertion generation:

- [x] synchronous keyword
- [x] auto security
- [x] dataResponse keyword

Child assertions:

- [x] td-data-schema_contentEncoding
- [x] td-data-schema_contentMediaType
- [x] td-data-schema_minLength
- [x] td-data-schema_maxLength
- [x] td-data-schema_multipleOf-IntegerSchema
- [x] td-data-schema_multipleOf-NumberSchema
- [x] td-data-schema_pattern
- [x] td-data-schema_exclusiveMaximum-IntegerSchema
- [x] td-data-schema_exclusiveMaximum-NumberSchema
- [x] td-data-schema_exclusiveMinimum-IntegerSchema
- [x] td-data-schema_exclusiveMinimum-NumberSchema
- [x] td-event-objects_dataResponse
- [x] td-event-names_dataResponse
- [x] td-objects_descriptions
- [x] td-objects_schemaDefinitions
- [x] td-objects_uriVariables
- [x] td-property-names_contentEncoding
- [x] td-property-names_contentMediaType
- [x] td-property-names_exclusiveMaximum
- [x] td-property-names_exclusiveMinimum
- [x] td-property-names_maxLength
- [x] td-property-names_minLength
- [x] td-property-names_multipleOf

TBC (@FadySalama you can also take a first stab at it to see what we need to implement here)

We can just mark the checkboxes as each assertion is implemented

**Comment by FadySalama** [comment]
@egekorkan @mmccool Many of the assertions listed here are not in the template.csv that I use to generate the manual.csv. Which means that both the template.csv and the manual.csv that we have in the wot-testing repository are faulty and incomplete.

**Comment by egekorkan** [comment]
So I think what happens is that the file depends.csv at https://github.com/w3c/wot-thing-description/blob/main/testing/inputs/depends.csv adds the child assertions which are not in the template.csv ? Hopefully soon I will automate the generation of https://github.com/w3c/wot-thing-description/blob/main/testing/assertions.csv even further so that we have a full list of assertions generated easily. But @mmccool please confirm :)

**Comment by mmccool** [comment]
Well, I feel dumb.  Should have read my own documentation...

You have to add "extra" assertions to the file testing/inputs/extra-asserts.html.  This basically is a regular HTML file (so you can read and interpret it with cheerio if you want in extractFile.js...) with rfc2119-assertion spans in it.  The basic pattern for child assertions is to add them here, then state dependences in depends.csv, then suppress any that you don't want (e.g that were added just to make testing easier) in suppressed.csv. 

We probably also want to look through the other assertions in extra-asserts.html as well and remove any that are obsolete.  Anyway, I added the contentEncoding one in my PR as a test case and regenerated the template.csv and it worked correctly.  I am going to go ahead and merge that PR and let you make another PR to update it as necessary, then I will rebase and update the implementation report again.
