### ISSUE TITLE
TM Validation fails when using `tm:required`

### ISSUE THREAD

**Issue by JKRhb** [thingweb/thingweb-playground#273]
When trying to validate TM that uses the `tm:required` feature, the validation seems to fail at the moment, emitting the following error messages:

```
data/tm:required/0 must match format "json-pointer"
{
  ID: Error: Invalid TM
      at checkTMVocabulary (.../thingweb-playground/packages/assertions/assertionTests-tm.js:295:15)
      at validateTM (.../thingweb-playground/packages/assertions/assertionTests-tm.js:76:25)
      at .../thingweb-playground/packages/assertions/index.js:174:39
      at Array.forEach (<anonymous>)
      at .../thingweb-playground/packages/assertions/index.js:158:23,
  Status: 'fail'
}
.../thingweb-playground/packages/assertions/assertionTests-tm.js:82
        throw new Error("Invalid TM")
              ^

Error: Invalid TM
    at validateTM (.../thingweb-playground/packages/assertions/assertionTests-tm.js:82:15)
    at .../thingweb-playground/packages/assertions/index.js:174:39
    at Array.forEach (<anonymous>)
    at .../thingweb-playground/packages/assertions/index.js:158:23
```

You can reproduce the problem with this minimal TM example:

```json
{
    "@context": ["https://www.w3.org/2022/wot/td/v1.1"], 
    "@type" : "tm:ThingModel",
    "title": "Lamp Thing Model",
    "tm:required": [
        "#/properties/status"
    ],
    "properties": {
        "status": {
            "type": "string"
        }
    }
}
```

**Comment by egekorkan** [comment]
we have seen that the use of `#` is not permitted in a json pointer. @JKRhb we are going to look at it in the TD spec but you may need to change your implementation. See the comments in the PR at testing

**Comment by FadySalama** [comment]
@egekorkan What is the status of this issue?

**Comment by egekorkan** [comment]
> @egekorkan What is the status of this issue?

We are fine. As seen in the linked PR, the comment https://github.com/w3c/wot-testing/pull/349#issuecomment-1176218192 (the last two bullet points) show that it is an issue that the examples need fixing. https://github.com/w3c/wot-thing-description/pull/1571 . Closing this issue
