### ISSUE TITLE
Validation of href vs base

### ISSUE THREAD

**Issue by sebastiankb** [thingweb/thingweb-playground#3]
@egekorkan So far, no validation is be done for a relative provided href and base URI. Also the correct "/" has to be checked. 
E.g., "base":"http://test-example.net" and "href":""test" is not correct since there is a "/" missing at the begin of href or end of the base uri

**Comment by egekorkan** [comment]
Corrected and pushed to http://plugfest.thingweb.io/playground/  . Now if you don't have a base you have to have absolute URLs in hrefs. If you have base ending with /, then hrefs should NOT start with /. If you have base ending without /, then you should have hrefs starting with /.

**Comment by sebastiankb** [comment]
Thanks
