### ISSUE TITLE
Update *valid* examples

### ISSUE THREAD

**Issue by danielpeintner** [thingweb/thingweb-playground#30]
I assume this is a *running* task as long as the TD itself is changing.

*Valid* examples linked on http://plugfest.thingweb.io/playground/ might need to be updated from time to time.

**Comment by egekorkan** [comment]
Started working on it at https://github.com/egekorkan/thingweb-playground/tree/princeton-testfest

**Comment by egekorkan** [comment]
Fixed by #31
