### ISSUE TITLE
pattern does not detect oneOf

### ISSUE THREAD

**Issue by egekorkan** [thingweb/thingweb-playground#320]
assertion to check pattern does not go into oneOf where it should

**Comment by egekorkan** [comment]
This is actually for all new data schema terms. @FadySalama can you fix this? I think you have added most of the new terms and removed the else part that you can see in the older ones: https://github.com/thingweb/thingweb-playground/blob/master/packages/assertions/assertions-td/td-vocab-const--DataSchema.json 

The new ones do not have else and do not take complicated case into account https://github.com/thingweb/thingweb-playground/blob/master/packages/assertions/assertions-td/td-vocab-default--DataSchema.json#L64

**Comment by FadySalama** [comment]
I see, I may have removed it because I felt it is redundant but it seems it isn't. I will fix it
