### ISSUE TITLE
Add Netlify render

### ISSUE THREAD

**Issue by egekorkan** [thingweb/thingweb-playground#335]
It is annoying to review PRs without a live rendering procedure. Screenshots are not bad but a Netlify integration would be nice to allow clickable builds.

**Comment by egekorkan** [comment]
I have started this. A non running version for now that should work later on is available at https://code.siemens.com/iot/wot-website/-/tree/redesign

**Comment by egekorkan** [comment]
This should be working now. @fatadel can you push a commit to one of your PRs?

**Comment by fatadel** [comment]
> This should be working now. @fatadel can you push a commit to one of your PRs?

Done - https://github.com/thingweb/thingweb-playground/pull/334. Wow, seems to work just fine! 🎉

**Comment by egekorkan** [comment]
Just saw it, looking neat! Closing
