### ISSUE TITLE
Changing the save methodology

### ISSUE THREAD

**Issue by egekorkan** [thingweb/thingweb-playground#353]
Saving via gists is not bad but it has some problems:
- We need to have a running backend. Not a problem for now but it would be nice to move away from the current hosting solution and move to something like netlify to better serve the globe.
- We need to manage auth tokens
- There is an ownership transfer with possible privacy problems

It would be better to change it so that a URL fragment is appended to the side which is an encoded version of the TD. This way, we can also put very long TDs. A basic URL encoding would fail for long TDs. 

Some examples that can be taken as good examples:
- https://www.jsonschemavalidator.net/
- https://regex101.com/

**Comment by fatadel** [comment]
@egekorkan Both examples you've shared seem to use a backend for the save functionality. They save the state on their backend and give you an id to fetch it later (for example, https://www.jsonschemavalidator.net/s/poD5PPIw or https://regex101.com/r/lO3TMg/1).
A URL fragment indeed does not seem to have any length limitations and we could simply encode data there. Should I go this way or the way the example websites do?

**Comment by egekorkan** [comment]
Hmm that is sad. I think that an encoding might be still helpful in order to reduce the length of the URI. It is true that URL fragment does not seem to have a length as long as it is not sent to the server, which will not be in this case.

Also, this would be a valid use case for the canonicalisation topics that are postponed to TD 2.0. If we are saving the TD somewhere, we should guarantee that it will be the same TD when received back. Meaning that the TD should be the same in text (or bytes), not just in JSON.

@fatadel could you integrate this kind of transformation function in core first and then use it in the web? This way, it can be also used from CLI
