### ISSUE TITLE
JUnit Style Output for CLI package?

### ISSUE THREAD

**Issue by edbingo** [thingweb/thingweb-playground#396]
The output of a JUnit style XML file would make this very useful for a pipeline, this could be implemented with a flag for the CLI and using [junit-report-builder](https://www.npmjs.com/package/junit-report-builder).

**Comment by egekorkan** [comment]
Thank you for the suggestion, this indeed makes sense and I will add this to our list

**Comment by egekorkan** [comment]
Also makes sense to download this kind of result from the web interface, which would help with some bug reports we receive of unexplained validation results.

**Comment by egekorkan** [comment]
This is done in #398
