### ISSUE TITLE
Take multiple inputs from CLI

### ISSUE THREAD

**Issue by edbingo** [thingweb/thingweb-playground#397]
It would be useful if you could pass multiple files / folders with the input flag. This seems like an easy fix using a for/of loop.

**Comment by egekorkan** [comment]
This is actually already possible with the `-i` parameter. Please see https://github.com/thingweb/thingweb-playground/tree/master/packages/cli#parameters

**Comment by edbingo** [comment]
This doesn't seem to be working for me:

```
> node packages/cli/index.js -i packages/core/examples/tms/valid/affordances.json packages/core/examples/tms/valid/security.json
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received an instance of Array
```

**Comment by egekorkan** [comment]
Sorry, I have misunderstood your comment. Currently, you can either specify a single file or a single folder. You want to pass multiple file names right?

**Comment by edbingo** [comment]
Exactly. This could be done pretty unintrusively with a for/of loop:
```javascript
let inputArray = myArguments.input

if (myArguments.type === 'TD') {
    for (input of inputArray) {
        if (myArguments.assertions === true) {
            tdAssertionReport(input)
        }
        else if (myArguments.openApi === true) {
            openApiGeneration(input)
        }
        else if (myArguments.asyncApi === true) {
            asyncApiGeneration(input)
        }
        else if (myArguments.defaultAdd === true || myArguments.defaultRem === true) {
            defaultManipulation(input)
        }
        else {
            coreValidation(input)
        }
    }
}
```
See [here](https://github.com/edbingo/thingweb-playground/blob/input-array/packages/cli/index.js)

**Comment by egekorkan** [comment]
This looks good to me, can you add a corresponding test as well?
