### ISSUE TITLE
Uniqueness does not check with security definitions

### ISSUE THREAD

**Issue by egekorkan** [thingweb/thingweb-playground#75]

**Comment by egekorkan** [comment]
This is indicated only in the explanation of map Of where it says that every map of should have unique keys.
This includes checking uriVariables, securityDefinitions. 
Solution for uriVariables is complex but for securityDefinitions, just do the same as interactions

**Comment by egekorkan** [comment]
td-context-ns-securityscheme-prefix states this as well

**Comment by egekorkan** [comment]
@adriankast, could you add this to the additional validation check named propUniqueness?

**Comment by adriankast** [comment]
Is implemented https://github.com/adriankast/thingweb-playground/commit/0f31870e9c42036b8b1746d1daeec207f3837fa8
Should it also pass an assertion (e.g. `td-context-ns-securityscheme-prefix_uniqueness`)?

**Comment by egekorkan** [comment]
There isn't an assertion named `td-context-ns-securityscheme-prefix`? In any case, the assertions that start like that are about the value of `@context`

**Comment by adriankast** [comment]
> 
> 
> td-context-ns-securityscheme-prefix states this as well

Oh okay, is was thinking so, because of the comment. Then it should be implemented with the next PR.

**Comment by egekorkan** [comment]
Deployed!
