### ISSUE TITLE
bcp47 is not validated in the Web version

### ISSUE THREAD

**Issue by egekorkan** [thingweb/thingweb-playground#98]

**Comment by egekorkan** [comment]
Solution proposals: https://www.npmjs.com/package/bcp47-validate

**Comment by adriankast** [comment]
With [PR125](https://github.com/thingweb/thingweb-playground/pull/125) part of the additional validations (as it is part of the checkMultiLang function).

**Comment by egekorkan** [comment]
This does not seem to be fixed, i.e. when I paste the following TD, all checks pass:
```json
{
    "@context": "https://www.w3.org/2019/wot/td/v1",
    "securityDefinitions": {
        "basic_sc": {
            "scheme": "basic",
            "in": "header"
        }
    },
    "security": "basic_sc",
    "title": "MyThing",
    "titles": {
        "enasdasd":"MyThing",
        "de": "MeinDing",
        "ja" : "私の物",
        "zh-Hans" : "我的东西", 
        "zh-Hant" : "我的東西"
    },
    "descriptions": {
        "enasdasd":"Human readable information.",
        "de": "Menschenlesbare Informationen.",
        "ja" : "人間が読むことができる情報",
        "zh-Hans" : "人们可阅读的信息", 
        "zh-Hant" : "人們可閱讀的資訊"
    }
}
```

**Comment by adriankast** [comment]
You are right, the current pattern check seems to be broken, if you use `enasdasdd` with another `d` at the end, it throws an error, but for many wrong variants it doesn't.

**Comment by egekorkan** [comment]
Interesting :) Sadly the above library uses the same pattern, see here: https://github.com/SafetyCulture/bcp47/blob/e1afa0b61f932462f46c87195c746b0aade467ac/src/index.js#L1

**Comment by adriankast** [comment]
Mhm doesn't make it easier^^ 
Could it be that the tag you used for testing is actually fine?
I just had a short look at https://tools.ietf.org/html/bcp47 and it seems to describe only the general structure of an bcp47 tag, which also allows "private" parts, so could it be that "enasdasd" is considered an private tag?
Since, e.g., `de_DE` instead of `de-DE` throws an error, maybe there is no problem with the validation?

**Comment by egekorkan** [comment]
I see! Makes sense :) Can be closed
